# NumPy: masyvai (arrays) ir jų savybės

Šiame faile pateikiami pagrindiniai NumPy masyvų (array) principai: masyvų savybės ir dažniausi masyvų kūrimo būdai.

In [14]:
import numpy as np

## 1. Masyvo (array) savybės

Dažniausiai naudojamos savybės:

- **ndim** – masyvo dimensijų (ašių) skaičius.
- **shape** – masyvo forma (kiek elementų yra kiekvienoje dimensijoje).
- **size** – bendras elementų skaičius.
- **dtype** – elementų duomenų tipas.

In [20]:
# Paprastas 1D masyvas (vienos dimensijos)
a = np.array([10, 20, 30, 10, 20, 45])

print("a =", a)
print("a.ndim  =", a.ndim)   # dimensijų skaičius
print("a.shape =", a.shape)  # forma
print("a.size  =", a.size)   # elementų kiekis
print("a.dtype =", a.dtype)  # duomenų tipas

a = [10 20 30 10 20 45]
a.ndim  = 1
a.shape = (6,)
a.size  = 6
a.dtype = int32


In [ ]:
# 2D masyvas (dvi dimensijos, dažnai vadinamas matrica)
b = np.array([
    [1, 2, 3],
    [4, 5, 6]
])
print(b)
print("b =\n", b)
print("b.ndim  =", b.ndim)
print("b.shape =", b.shape)  # 2 eilutės, 3 stulpeliai
print("b.size  =", b.size)   # 2 * 3 = 6 elementai
print("b.dtype =", b.dtype)

[['1' '2' '3']
 ['4' '5' 'b6']]
b =
 [['1' '2' '3']
 ['4' '5' 'b6']]
b.ndim  = 2
b.shape = (2, 3)
b.size  = 6
b.dtype = <U11


### Pastaba apie **dtype**

NumPy dažniausiai parenka tipą automatiškai pagal pateiktas reikšmes. Jei masyve yra skirtingų tipų reikšmės,
NumPy parenka tipą, kuris gali sutalpinti viską (pvz., `int` ir `float` kartu dažniausiai virsta į `float`).

In [25]:
c = np.array([1, 2, 3.5])  # yra float reikšmė, todėl visas masyvas tampa float tipo

print("c =", c)
print("c.dtype =", c.dtype)

c = [1.  2.  3.5]
c.dtype = float64


## 2. Masyvų kūrimas (array creation)

Žemiau pateikti dažniausiai naudojami masyvų kūrimo metodai.

### 2.1 `np.array`

Sukuria masyvą iš Python sąrašo (list) ar kitų iteruojamų struktūrų.

In [26]:
x = np.array([5, 10, 15])
y = np.array([[1, 2], [3, 4]])

print("x =", x)
print("y =\n", y)

x = [ 5 10 15]
y =
 [[1 2]
 [3 4]]


### 2.2 `np.ones`

Sukuria masyvą, užpildytą vienetais. Pagal nutylėjimą tipas yra `float`.

In [27]:
ones_1d = np.ones(5)        # 1D masyvas iš 5 vienetų
ones_2d = np.ones((2, 3))   # 2D masyvas: 2x3

print("ones_1d =", ones_1d)
print("ones_2d =\n", ones_2d)
print("ones_2d.dtype =", ones_2d.dtype)

ones_1d = [1. 1. 1. 1. 1.]
ones_2d =
 [[1. 1. 1.]
 [1. 1. 1.]]
ones_2d.dtype = float64


### 2.3 `np.zeros`

Sukuria masyvą, užpildytą nuliais. Pagal nutylėjimą tipas yra `float`.

In [28]:
zeros_1d = np.zeros(4)
zeros_2d = np.zeros((3, 2))

print("zeros_1d =", zeros_1d)
print("zeros_2d =\n", zeros_2d)

zeros_1d = [0. 0. 0. 0.]
zeros_2d =
 [[0. 0.]
 [0. 0.]
 [0. 0.]]


### 2.4 `np.arange`

Sukuria skaičių seką intervale `[start, stop)`, t. y. **stop reikšmė neįtraukiama**.
Žingsnis nurodomas per `step`.

In [31]:
seq1 = np.arange(0, 10, 1)        # 0, 1, 2, ..., 9
seq2 = np.arange(2, 11, 2)     # 2, 4, 6, 8, 10

print("seq1 =", seq1)
print("seq2 =", seq2)

seq1 = [0 1 2 3 4 5 6 7 8 9]
seq2 = [ 2  4  6  8 10]


### 2.5 `np.linspace`

Sukuria **nurodytą kiekį** tolygiai išdėstytų reikšmių intervale `[start, stop]`.
Pagal nutylėjimą **stop reikšmė įtraukiama**.

In [32]:
lin1 = np.linspace(0, 1, 5)      # 5 reikšmės nuo 0 iki 1
lin2 = np.linspace(10, 20, 3)    # 10, 15, 20

print("lin1 =", lin1)
print("lin2 =", lin2)

lin1 = [0.   0.25 0.5  0.75 1.  ]
lin2 = [10. 15. 20.]


## 3. `reshape`: formos keitimas

`reshape` pakeičia masyvo formą, **nekeičiant elementų kiekio**.
Todėl naujos formos elementų sandauga turi sutapti su `size`.

In [37]:
# Pradinis 1D masyvas su 6 elementais
r = np.arange(1, 17)   # [1, 2, 3, 4, 5, 6]

print("r =", r)
print("r.shape =", r.shape)

r = [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16]
r.shape = (16,)


In [34]:
# Formos pakeitimas į 2x3
r_2x3 = r.reshape(2, 3)

print("r_2x3 =\n", r_2x3)
print("r_2x3.shape =", r_2x3.shape)

r_2x3 =
 [[1 2 3]
 [4 5 6]]
r_2x3.shape = (2, 3)


In [35]:
# Formos pakeitimas į 3x2
r_3x2 = r.reshape(3, 2)

print("r_3x2 =\n", r_3x2)
print("r_3x2.shape =", r_3x2.shape)

r_3x2 =
 [[1 2]
 [3 4]
 [5 6]]
r_3x2.shape = (3, 2)


### `reshape(-1, n)` ir `reshape(m, -1)`

`-1` reiškia, kad viena dimensija apskaičiuojama automatiškai pagal likusias dimensijas ir elementų kiekį.

In [38]:
# Automatinis eilučių skaičiaus parinkimas, kai stulpelių skaičius fiksuotas
r_auto_rows = r.reshape(-1, 2)   # stulpeliai = 2, eilutės apskaičiuojamos automatiškai

print("r_auto_rows =\n", r_auto_rows)
print("r_auto_rows.shape =", r_auto_rows.shape)

r_auto_rows =
 [[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]
 [11 12]
 [13 14]
 [15 16]]
r_auto_rows.shape = (8, 2)


## 4. Greita santrauka

- **ndim** – kiek dimensijų turi masyvas.
- **shape** – masyvo forma.
- **size** – bendras elementų kiekis.
- **dtype** – elementų tipas.
- Dažniausi kūrimo metodai: `np.array`, `np.ones`, `np.zeros`, `np.arange`, `np.linspace`.
- `reshape` keičia formą, bet ne elementų skaičių.