# NumPy: indeksavimas, operacijos ir agregavimas

Šiame faile pateikiami pagrindiniai NumPy masyvų (array) naudojimo principai: indeksavimas, rėžiai (slicing),
operacijos, filtravimas, reikšmių keitimas, `np.where`, agregavimo metodai ir keli dažni masyvų funkcijų pavyzdžiai.

In [18]:
import numpy as np

## 1. Array indexing (indeksavimas)

NumPy indeksavimas yra panašus į Python sąrašo (list) indeksavimą:

- Pirmas elementas turi indeksą **0**.
- Neigiamas indeksas skaičiuoja nuo galo: **-1** reiškia paskutinį elementą.

In [19]:
a = np.array([10, 20, 30, 40, 50])

print("a =", a)
print("a[0]  =", a[0])   # pirmas elementas
print("a[2]  =", a[2])   # trečias elementas
print("a[-1] =", a[-1])  # paskutinis elementas

a = [10 20 30 40 50]
a[0]  = 10
a[2]  = 30
a[-1] = 50


### 2D masyvo indeksavimas

2D masyve naudojami du indeksai: `[eilutė, stulpelis]`.

In [20]:
b = np.array([
    [1,  2,  3],
    [4,  5,  6],
    [7,  8,  9]
])

print("b =\n", b)
print("b[0, 0] =", b[0, 0])   # 1 (pirma eilutė, pirmas stulpelis)
print("b[1, 2] =", b[1, 2])   # 6 (antra eilutė, trečias stulpelis)
print("b[-1, -1] =", b[-1, -1])  # 9 (paskutinė eilutė, paskutinis stulpelis)

b =
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
b[0, 0] = 1
b[1, 2] = 6
b[-1, -1] = 9


## 2. Indexing and slicing (rėžiai)

Slicing sintaksė: `start:stop:step`

- `start` įtraukiamas.
- `stop` neįtraukiamas.
- `step` yra pasirenkamas (pagal nutylėjimą 1).

In [21]:
x = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

print("x =", x)
print("x[2:6] =", x[2:6])      # elementai su indeksais 2,3,4,5
print("x[:4]  =", x[:4])       # nuo pradžios iki 4 (neįtraukiant)
print("x[5:]  =", x[5:])       # nuo 5 iki galo
print("x[::2] =", x[::2])      # kas antras elementas
print("x[::-1] =", x[::-1])    # apsukimas atgaline tvarka

x = [0 1 2 3 4 5 6 7 8 9]
x[2:6] = [2 3 4 5]
x[:4]  = [0 1 2 3]
x[5:]  = [5 6 7 8 9]
x[::2] = [0 2 4 6 8]
x[::-1] = [9 8 7 6 5 4 3 2 1 0]


### Slicing 2D masyve

Rėžiai gali būti taikomi ir eilutėms, ir stulpeliams: `b[eilučių_rėžis, stulpelių_rėžis]`.

In [22]:
print("b =\n", b)
print("Pirmos dvi eilutės:\n", b[:2, :])
print("Pirmi du stulpeliai:\n", b[:, :2])
print("Vidurinis 2x2 blokas:\n", b[0:2, 1:3])

b =
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Pirmos dvi eilutės:
 [[1 2 3]
 [4 5 6]]
Pirmi du stulpeliai:
 [[1 2]
 [4 5]
 [7 8]]
Vidurinis 2x2 blokas:
 [[2 3]
 [5 6]]


## 3. Array operations (operacijos su masyvais)

NumPy leidžia atlikti aritmetines operacijas elementų lygiu (element-wise):

- Sudėtis, atimtis, daugyba, dalyba.
- Operacijos su skaičiumi taikomos visiems elementams.

In [23]:
p = np.array([1, 2, 3, 4])
q = np.array([10, 20, 30, 40])

print("p =", p)
print("q =", q)

print("p + q =", p + q)     # elementų suma
print("q - p =", q - p)     # elementų skirtumas
print("p * 2 =", p * 2)     # daugyba iš skaičiaus
print("q / 10 =", q / 10)   # dalyba iš skaičiaus (rezultatas dažnai tampa float)

p = [1 2 3 4]
q = [10 20 30 40]
p + q = [11 22 33 44]
q - p = [ 9 18 27 36]
p * 2 = [2 4 6 8]
q / 10 = [1. 2. 3. 4.]


### Lyginimo operacijos

Lyginimo rezultatas yra boolean tipo masyvas (`True` / `False`).

In [24]:
values = np.array([3, 7, 2, 9, 5])

print("values =", values)
print("values > 5 =", values > 5)
print("values == 7 =", values == 7)

values = [3 7 2 9 5]
values > 5 = [False  True False  True False]
values == 7 = [False  True False False False]


## 4. Filtering arrays (filtravimas)

Filtravimas dažniausiai daromas su boolean kauke.

In [25]:
values = np.array([3, 7, 2, 9, 5])

mask = values > 5
filtered = values[mask]

print("values =", values)
print("mask =", mask)
print("values[mask] =", filtered)

values = [3 7 2 9 5]
mask = [False  True False  True False]
values[mask] = [7 9]


### Sudėtingesnė sąlyga

Naudojant `&` ir `|` reikia skliaustų, nes kiekviena sąlyga turi būti atskirai apskliausta.

In [26]:
values = np.array([3, 7, 2, 9, 5, 8, 1])

mask_between = (values >= 3) & (values <= 8)
print("values =", values)
print("mask_between =", mask_between)
print("values[mask_between] =", values[mask_between])

values = [3 7 2 9 5 8 1]
mask_between = [ True  True False False  True  True False]
values[mask_between] = [3 7 5 8]


## 5. Modifying array values (reikšmių keitimas)

Reikšmės gali būti keičiamos pagal indeksą arba pagal boolean kaukę.

In [28]:
m = np.array([10, 20, 30, 40, 50])
print("Pradinis m =", m)

m[1] = 999  # pakeičiama viena reikšmė pagal indeksą
print("Po m[1] = 999:", m)

m[m > 40] = 0  # pakeičiamos visos reikšmės, kurios tenkina sąlygą
print("Po m[m >= 40] = 0:", m)
m

Pradinis m = [10 20 30 40 50]
Po m[1] = 999: [ 10 999  30  40  50]
Po m[m >= 40] = 0: [10  0 30 40  0]


array([10,  0, 30, 40,  0])

## 6. `np.where()`

`np.where(condition, value_if_true, value_if_false)` grąžina masyvą,
kuriame pagal sąlygą parenkama viena iš dviejų reikšmių.

Šis metodas patogus, kai reikia sukurti naują masyvą pagal taisyklę.

In [29]:
scores = np.array([40, 55, 70, 90, 30])

result = np.where(scores >= 60, "Pass", "Fail")

print("scores =", scores)
print("result =", result)

scores = [40 55 70 90 30]
result = ['Fail' 'Fail' 'Pass' 'Pass' 'Fail']


### `np.where()` naudojimas reikšmių perrašymui

Viena iš dažnų situacijų: visoms reikšmėms, kurios neatitinka sąlygos, priskirti kitą reikšmę.

In [30]:
values = np.array([5, -2, 7, -1, 0])

# Neigiamas reikšmes pakeičia į 0, o kitas palieka kaip yra
non_negative = np.where(values < 0, 0, values)

print("values =", values)
print("non_negative =", non_negative)

values = [ 5 -2  7 -1  0]
non_negative = [5 0 7 0 0]


## 7. Array aggregation methods (agregavimo metodai)

Agregavimo metodai grąžina vieną skaičių, apibendrinantį masyvą:

- `sum()` – suma
- `mean()` – vidurkis
- `min()` / `max()` – mažiausia / didžiausia reikšmė
- `std()` – standartinis nuokrypis

In [33]:
data = np.array([2, 4, 6, 8, 10])

print("data =", data)
print("sum  =", data.sum())
print("mean =", data.mean())
print("min  =", data.min())
print("max  =", data.max())
print("std  =", data.std().round(2))

data = [ 2  4  6  8 10]
sum  = 30
mean = 6.0
min  = 2
max  = 10
std  = 2.83


### Agregavimas 2D masyve ir `axis`

2D masyve dažnai norima agreguoti:

- pagal eilutes (`axis=1`)
- pagal stulpelius (`axis=0`)

`axis=0` reiškia agregavimą „žemyn“ per eilutes, todėl gaunamas rezultatas kiekvienam stulpeliui.
`axis=1` reiškia agregavimą „į šoną“ per stulpelius, todėl gaunamas rezultatas kiekvienai eilutei.

In [34]:
mat = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

print("mat =\n", mat)
print("Suma pagal stulpelius (axis=0):", mat.sum(axis=0))  # [1+4, 2+5, 3+6]
print("Suma pagal eilutes (axis=1):", mat.sum(axis=1))    # [1+2+3, 4+5+6]

mat =
 [[1 2 3]
 [4 5 6]]
Suma pagal stulpelius (axis=0): [5 7 9]
Suma pagal eilutes (axis=1): [ 6 15]


## 8. Array functions (dažnos funkcijos)

Žemiau pateikti keli pavyzdžiai su dažnomis NumPy funkcijomis:

- `np.unique` – unikalios reikšmės
- `np.sort` – rikiavimas
- `np.clip` – reikšmių apribojimas intervale
- `np.concatenate` – masyvų sujungimas

In [35]:
arr = np.array([3, 1, 2, 3, 2, 2, 5])

print("arr =", arr)
print("unique =", np.unique(arr))
print("sorted =", np.sort(arr))

arr = [3 1 2 3 2 2 5]
unique = [1 2 3 5]
sorted = [1 2 2 2 3 3 5]


In [36]:
vals = np.array([-5, 0, 3, 10, 15])

# Apriboja reikšmes intervale [0, 10]
clipped = np.clip(vals, 0, 10)

print("vals =", vals)
print("clipped =", clipped)

vals = [-5  0  3 10 15]
clipped = [ 0  0  3 10 10]


In [37]:
a1 = np.array([1, 2, 3])
a2 = np.array([4, 5])

combined = np.concatenate([a1, a2])

print("a1 =", a1)
print("a2 =", a2)
print("combined =", combined)

a1 = [1 2 3]
a2 = [4 5]
combined = [1 2 3 4 5]


## 9. Trumpa santrauka

- Indeksavimas: `a[i]`, 2D atveju `b[row, col]`.
- Slicing: `start:stop:step`, 2D atveju `b[rows, cols]`.
- Operacijos taikomos elementų lygiu.
- Filtravimas atliekamas su boolean kauke: `values[mask]`.
- Reikšmės gali būti keičiamos pagal indeksus arba pagal sąlygą.
- `np.where()` leidžia patogiai sukurti arba transformuoti masyvą pagal taisyklę.
- Agregavimo metodai (`sum`, `mean`, `min`, `max`, ...) apibendrina duomenis.
- Dažnos funkcijos: `unique`, `sort`, `clip`, `concatenate`.