# NumPy: rikiavimas, vektorizacija, broadcasting ir matricų operacijos

Šiame faile pateikiami praktiniai pavyzdžiai: masyvų rikiavimas, vektorizacija (paprastai),
broadcasting (paprastai), operacijos su matricomis, transponavimas, elementų lygio funkcijos ir dažni metodai
(matematiniai, statistiniai, boolean).

In [ ]:
import numpy as np

## 1. Sorting arrays (masyvų rikiavimas)

Dažniausi rikiavimo būdai:

- `np.sort(a)` grąžina **naują** surikiuotą masyvą.
- `a.sort()` surikiuoja **vietoje** (in-place) ir nekeičia kintamojo nuorodos.
- `np.argsort(a)` grąžina indeksus, pagal kuriuos masyvą būtų galima surikiuoti.

In [ ]:
a = np.array([4, 1, 7, 3, 3, 9])

sorted_a = np.sort(a)

print("a =", a)
print("np.sort(a) =", sorted_a)   # originalas nepasikeitė

In [ ]:
b = np.array([4, 1, 7, 3, 3, 9])

b.sort()  # rikiuoja vietoje

print("b (po b.sort()) =", b)

In [ ]:
a = np.array([40, 10, 70, 30])

idx = np.argsort(a)  # indeksai, kurie rūšiuoja masyvą

print("a =", a)
print("argsort indeksai =", idx)
print("a pagal indeksus =", a[idx])

### Rikiavimas 2D masyve

`np.sort(mat, axis=0)` rikiuoja kiekvieną stulpelį atskirai.
`np.sort(mat, axis=1)` rikiuoja kiekvieną eilutę atskirai.

In [ ]:
mat = np.array([
    [3, 1, 2],
    [9, 5, 6],
    [4, 8, 7]
])

print("mat =\n", mat)
print("Rikiavimas pagal stulpelius (axis=0):\n", np.sort(mat, axis=0))
print("Rikiavimas pagal eilutes (axis=1):\n", np.sort(mat, axis=1))

## 2. Vectorization (vektorizacija)

Vektorizacija reiškia, kad vietoje `for` ciklo atliekama operacija su visu masyvu vienu veiksmu.
Tokios operacijos dažniausiai yra:

- trumpesnės
- aiškesnės
- greitesnės, nes NumPy naudoja optimizuotas vidines funkcijas

In [20]:
values = np.array([1, 2, 3, 4, 5])

# Vektorizuota operacija: kiekvienas elementas pakeliamas kvadratu
squared = values ** 2

print("values =", values)
print("squared =", squared)

values = [1 2 3 4 5]
squared = [ 1  4  9 16 25]


In [21]:
# Tas pats rezultatas su ciklu (dėl palyginimo)
values = np.array([1, 2, 3, 4, 5])

out = []
for v in values:
    out.append(v ** 2)

print("su ciklu =", np.array(out))

su ciklu = [ 1  4  9 16 25]


## 3. Broadcasting (broadcasting) 

Broadcasting reiškia, kad NumPy leidžia atlikti operacijas tarp masyvų skirtingų formų,
kai tai logiškai įmanoma. Dažniausias atvejis:

- masyvas + skaičius (skaičius pritaikomas kiekvienam elementui)
- matrica + vektorius (vektorius pritaikomas kiekvienai eilutei arba stulpeliui)

In [22]:
x = np.array([10, 20, 30])

# Skaičius 5 pridedamas prie kiekvieno elemento
print("x =", x)
print("x + 5 =", x + 5)

x = [10 20 30]
x + 5 = [15 25 35]


In [23]:
mat = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

add_row = np.array([10, 20, 30])  # forma (3,)

# Vektorius pridedamas prie kiekvienos eilutės (eilutė po eilutės)
result = mat + add_row

print("mat =\n", mat)
print("add_row =", add_row)
print("mat + add_row =\n", result)

mat =
 [[1 2 3]
 [4 5 6]]
add_row = [10 20 30]
mat + add_row =
 [[11 22 33]
 [14 25 36]]


## 4. Operacijos su matricomis

Skiriamos dvi svarbios operacijų grupės:

- **elementų lygio (element-wise)**: `A + B`, `A * B` (kai formos sutampa)
- **matricų sandauga (matrix multiplication)**: `A @ B` (kai matmenys suderinami)

In [24]:
A = np.array([
    [1, 2],
    [3, 4]
])

B = np.array([
    [10, 20],
    [30, 40]
])

print("A =\n", A)
print("B =\n", B)

# Elementų lygio sudėtis ir daugyba
print("A + B =\n", A + B)
print("A * B (element-wise) =\n", A * B)

A =
 [[1 2]
 [3 4]]
B =
 [[10 20]
 [30 40]]
A + B =
 [[11 22]
 [33 44]]
A * B (element-wise) =
 [[ 10  40]
 [ 90 160]]


In [25]:
# Matricų sandauga su @
A = np.array([
    [1, 2],
    [3, 4]
])

B = np.array([
    [10, 20],
    [30, 40]
])

print("A @ B =\n", A @ B)

A @ B =
 [[ 70 100]
 [150 220]]


### Matrica ir skaliaras (skaičius)

Skaliaras pritaikomas kiekvienam elementui.

In [26]:
M = np.array([
    [2, 4, 6],
    [1, 3, 5]
])

print("M =\n", M)
print("M * 10 =\n", M * 10)
print("M + 1 =\n", M + 1)

M =
 [[2 4 6]
 [1 3 5]]
M * 10 =
 [[20 40 60]
 [10 30 50]]
M + 1 =
 [[3 5 7]
 [2 4 6]]


### Matricos transponavimas

Transponavimas sukeičia eilutes ir stulpelius. Tam naudojamas `.T`.

In [27]:
M = np.array([
    [2, 4, 6],
    [1, 3, 5]
])

print("M =\n", M)
print("M.T =\n", M.T)
print("M.shape =", M.shape)
print("M.T.shape =", M.T.shape)

M =
 [[2 4 6]
 [1 3 5]]
M.T =
 [[2 1]
 [4 3]
 [6 5]]
M.shape = (2, 3)
M.T.shape = (3, 2)


## 5. Element-wise funkcijos (dažnos duomenų analitikoje)

Elementų lygio funkcijos pritaikomos kiekvienam elementui atskirai.

Dažnos funkcijos:
- `np.abs` – absoliuti reikšmė
- `np.round` – apvalinimas
- `np.sqrt` – šaknis
- `np.log` – natūrinis logaritmas
- `np.exp` – e laipsnis
- `np.clip` – apribojimas intervale

In [28]:
vals = np.array([-2.7, -1.2, 0.0, 1.4, 3.9])

print("vals =", vals)
print("abs =", np.abs(vals))
print("round(1) =", np.round(vals))
print("clip [0, 3] =", np.clip(vals, 0, 3))

vals = [-2.7 -1.2  0.   1.4  3.9]
abs = [2.7 1.2 0.  1.4 3.9]
round(1) = [-3. -1.  0.  1.  4.]
clip [0, 3] = [0.  0.  0.  1.4 3. ]


In [29]:
pos = np.array([1, 4, 9, 16])

print("pos =", pos)
print("sqrt =", np.sqrt(pos))
print("log =", np.log(pos))
print("exp =", np.exp(np.array([0, 1, 2])))

pos = [ 1  4  9 16]
sqrt = [1. 2. 3. 4.]
log = [0.         1.38629436 2.19722458 2.77258872]
exp = [1.         2.71828183 7.3890561 ]


## 6. Metodai: matematiniai ir statistiniai

Dažniausi agregavimo metodai:

- `sum`, `mean`, `min`, `max`
- `median` (mediana)
- `std` (standartinis nuokrypis)
- `var` (dispersija)

Naudojant `axis` galima agreguoti pagal eilutes arba stulpelius.

In [30]:
data = np.array([5, 2, 9, 1, 7])

print("data =", data)
print("sum =", data.sum())
print("mean =", data.mean())
print("min =", data.min())
print("max =", data.max())
print("median =", np.median(data))
print("std =", data.std())
print("var =", data.var())

data = [5 2 9 1 7]
sum = 24
mean = 4.8
min = 1
max = 9
median = 5.0
std = 2.9933259094191533
var = 8.96


In [31]:
mat = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

print("mat =\n", mat)
print("Vidurkis pagal stulpelius (axis=0):", mat.mean(axis=0))
print("Vidurkis pagal eilutes (axis=1):", mat.mean(axis=1))

mat =
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Vidurkis pagal stulpelius (axis=0): [4. 5. 6.]
Vidurkis pagal eilutes (axis=1): [2. 5. 8.]


## 7. Boolean metodai

Boolean masyvas dažnai gaunamas iš lyginimo sąlygų.
Tokiam masyvui dažnai naudojami metodai:

- `any()` – ar bent viena reikšmė yra `True`
- `all()` – ar visos reikšmės yra `True`
- `sum()` – kiek yra `True` (nes `True` laikomas kaip 1, o `False` kaip 0)

In [32]:
scores = np.array([40, 55, 70, 90, 30])

passed = scores >= 60

print("scores =", scores)
print("passed =", passed)

print("any passed =", passed.any())
print("all passed =", passed.all())
print("passed count =", passed.sum())

scores = [40 55 70 90 30]
passed = [False False  True  True False]
any passed = True
all passed = False
passed count = 2


### Boolean indeksavimas ir santrauka viename pavyzdyje

Dažna situacija: išfiltruoti reikšmes ir greitai suskaičiuoti kiek jų atitinka sąlygą.

In [33]:
prices = np.array([9.99, 14.50, 3.20, 25.00, 7.80])

mask = prices > 10
high_prices = prices[mask]

print("prices =", prices)
print("mask =", mask)
print("high_prices =", high_prices)
print("high_prices count =", mask.sum())
print("high_prices mean =", high_prices.mean())

prices = [ 9.99 14.5   3.2  25.    7.8 ]
mask = [False  True False  True False]
high_prices = [14.5 25. ]
high_prices count = 2
high_prices mean = 19.75


## 8. Trumpa santrauka

- Rikiavimas: `np.sort`, `a.sort`, `np.argsort`.
- Vektorizacija: operacijos atliekamos su visu masyvu be ciklų.
- Broadcasting: operacijos leidžiamos tarp suderinamų formų.
- Matricos operacijos: elementų lygio ir matricų sandauga su `@`.
- Transponavimas: `.T`.
- Elementų lygio funkcijos: `abs`, `round`, `sqrt`, `log`, `exp`, `clip`.
- Matematiniai ir statistiniai metodai: `sum`, `mean`, `median`, `std`, `var`.
- Boolean metodai: `any`, `all`, `sum`.