# NumPy: formos keitimas ir masyvų sujungimas / skaidymas

Šiame faile pateikiami praktiniai pavyzdžiai:
`reshape`, `flatten`, `ravel`, `concatenate`, `vstack`, `hstack`, keli sujungimo pagalbininkai
(stacking helpers) ir masyvų skaidymas (splitting).

In [1]:
import numpy as np

## 1. `reshape()`

`reshape` pakeičia masyvo formą, **nekeičiant elementų kiekio**.
Todėl naujos formos elementų sandauga turi sutapti su `size`.

In [2]:
a = np.arange(1, 13)  # 1..12
print("a =", a)
print("a.shape =", a.shape)
print("a.size =", a.size)

a = [ 1  2  3  4  5  6  7  8  9 10 11 12]
a.shape = (12,)
a.size = 12


In [3]:
# Formos pakeitimas į 3x4
a_3x4 = a.reshape(3, 4)
print("a_3x4 =\n", a_3x4)
print("a_3x4.shape =", a_3x4.shape)

a_3x4 =
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
a_3x4.shape = (3, 4)


In [4]:
# Automatinis vienos dimensijos parinkimas su -1
a_auto = a.reshape(2, -1)   # 2 eilutės, stulpelių skaičius apskaičiuojamas automatiškai
print("a_auto =\n", a_auto)
print("a_auto.shape =", a_auto.shape)

a_auto =
 [[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]
a_auto.shape = (2, 6)


## 2. `flatten()` ir `ravel()`

Abu metodai paverčia masyvą į 1D masyvą.

- `flatten()` visada grąžina **kopiją** (originalo nekeičia).
- `ravel()` dažnai grąžina **vaizdą** (view), todėl kai kuriais atvejais pakeitimai gali paveikti originalą.

Praktikoje, kai svarbu aiškumas, `flatten()` dažnai yra saugesnis pasirinkimas.

In [5]:
m = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

flat = m.flatten()
rav = m.ravel()

print("m =\n", m)
print("flatten() =", flat)
print("ravel()   =", rav)

m =
 [[1 2 3]
 [4 5 6]]
flatten() = [1 2 3 4 5 6]
ravel()   = [1 2 3 4 5 6]


In [6]:
# Pavyzdys, kaip keitimas gali elgtis skirtingai
m = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

flat = m.flatten()
rav = m.ravel()

flat[0] = 999
rav[1] = 888

print("Po pakeitimų:")
print("m =\n", m)          # ravel pakeitimas dažnai persiduoda į originalą
print("flat =", flat)      # flatten yra atskira kopija
print("rav  =", rav)

Po pakeitimų:
m =
 [[  1 888   3]
 [  4   5   6]]
flat = [999   2   3   4   5   6]
rav  = [  1 888   3   4   5   6]


## 3. `concatenate()`

`np.concatenate` sujungia masyvus pagal nurodytą ašį (`axis`).

- `axis=0` sujungia „vertikaliai“ (prideda eilutes), jei masyvai yra 2D.
- `axis=1` sujungia „horizontaliai“ (prideda stulpelius), jei masyvai yra 2D.

Sujungiami masyvai turi būti suderinami pagal kitus matmenis.

In [7]:
a = np.array([1, 2, 3])
b = np.array([4, 5])

c = np.concatenate([a, b])

print("a =", a)
print("b =", b)
print("concatenate([a, b]) =", c)

a = [1 2 3]
b = [4 5]
concatenate([a, b]) = [1 2 3 4 5]


In [8]:
A = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

B = np.array([
    [7, 8, 9]
])

# axis=0: prideda naują eilutę (t. y. sujungia pagal eilutes)
C = np.concatenate([A, B], axis=0)

print("A =\n", A)
print("B =\n", B)
print("C (axis=0) =\n", C)

A =
 [[1 2 3]
 [4 5 6]]
B =
 [[7 8 9]]
C (axis=0) =
 [[1 2 3]
 [4 5 6]
 [7 8 9]]


In [9]:
A = np.array([
    [1, 2],
    [3, 4]
])

B = np.array([
    [10],
    [20]
])

# axis=1: prideda stulpelį (t. y. sujungia pagal stulpelius)
C = np.concatenate([A, B], axis=1)

print("A =\n", A)
print("B =\n", B)
print("C (axis=1) =\n", C)

A =
 [[1 2]
 [3 4]]
B =
 [[10]
 [20]]
C (axis=1) =
 [[ 1  2 10]
 [ 3  4 20]]


## 4. `vstack()` ir `hstack()`

Tai patogūs trumpiniai, dažnai naudojami 2D masyvams:

- `np.vstack([A, B])` sujungia masyvus vertikaliai (kaip `axis=0`).
- `np.hstack([A, B])` sujungia masyvus horizontaliai (kaip `axis=1`).

Svarbu, kad matmenys būtų suderinami:
- `vstack` reikalauja vienodo stulpelių skaičiaus.
- `hstack` reikalauja vienodo eilučių skaičiaus.

In [10]:
A = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

B = np.array([
    [7, 8, 9]
])

print("vstack =\n", np.vstack([A, B]))

vstack =
 [[1 2 3]
 [4 5 6]
 [7 8 9]]


In [11]:
A = np.array([
    [1, 2],
    [3, 4]
])

B = np.array([
    [10, 20],
    [30, 40]
])

print("hstack =\n", np.hstack([A, B]))

hstack =
 [[ 1  2 10 20]
 [ 3  4 30 40]]


## 5. Stacking helpers (sujungimo pagalbininkai)

Dažnai naudojami pagalbininkai:

- `np.column_stack` – sujungia 1D masyvus į stulpelius (gaunamas 2D masyvas).
- `np.row_stack` – sujungia masyvus pagal eilutes (panašu į `vstack`).
- `np.dstack` – sujungia pagal trečią dimensiją (sudeda „sluoksniais“).

`column_stack` yra ypač naudingas, kai turimos kelios 1D sekos ir reikia suformuoti „lentelę“.

In [12]:
x = np.array([1, 2, 3])
y = np.array([10, 20, 30])

cols = np.column_stack([x, y])

print("x =", x)
print("y =", y)
print("column_stack([x, y]) =\n", cols)
print("shape =", cols.shape)

x = [1 2 3]
y = [10 20 30]
column_stack([x, y]) =
 [[ 1 10]
 [ 2 20]
 [ 3 30]]
shape = (3, 2)


In [13]:
A = np.array([
    [1, 2],
    [3, 4]
])

B = np.array([
    [5, 6]
])

rows = np.row_stack([A, B])

print("A =\n", A)
print("B =\n", B)
print("row_stack([A, B]) =\n", rows)

A =
 [[1 2]
 [3 4]]
B =
 [[5 6]]
row_stack([A, B]) =
 [[1 2]
 [3 4]
 [5 6]]


In [14]:
# dstack pavyzdys su dviem 2D masyvais (sujungimas į 3D)
A = np.array([
    [1, 2],
    [3, 4]
])

B = np.array([
    [10, 20],
    [30, 40]
])

stacked_3d = np.dstack([A, B])

print("A =\n", A)
print("B =\n", B)
print("dstack([A, B]) shape =", stacked_3d.shape)
print("dstack([A, B]) =\n", stacked_3d)

A =
 [[1 2]
 [3 4]]
B =
 [[10 20]
 [30 40]]
dstack([A, B]) shape = (2, 2, 2)
dstack([A, B]) =
 [[[ 1 10]
  [ 2 20]]

 [[ 3 30]
  [ 4 40]]]


## 6. Splitting an array (masyvo skaidymas)

Skaidymui naudojami metodai:

- `np.split` – padalina į lygias dalis (jei įmanoma) pagal `axis`.
- `np.array_split` – leidžia padalinti ir tada, kai dalys nebūtinai vienodos.
- `np.hsplit` – patogus trumpinys skaidymui horizontaliai (pagal stulpelius).
- `np.vsplit` – patogus trumpinys skaidymui vertikaliai (pagal eilutes).

In [15]:
arr = np.arange(1, 13)  # 1..12

parts = np.split(arr, 3)  # 12 elementų dalinami į 3 lygias dalis po 4

print("arr =", arr)
print("split į 3 dalis:")
for i, p in enumerate(parts, start=1):
    print(f"  dalis {i}:", p)

arr = [ 1  2  3  4  5  6  7  8  9 10 11 12]
split į 3 dalis:
  dalis 1: [1 2 3 4]
  dalis 2: [5 6 7 8]
  dalis 3: [ 9 10 11 12]


In [16]:
arr = np.arange(1, 11)  # 1..10

# 10 elementų į 3 dalis nepasidalina lygiai, todėl naudojamas array_split
parts = np.array_split(arr, 3)

print("arr =", arr)
print("array_split į 3 dalis:")
for i, p in enumerate(parts, start=1):
    print(f"  dalis {i}:", p)

arr = [ 1  2  3  4  5  6  7  8  9 10]
array_split į 3 dalis:
  dalis 1: [1 2 3 4]
  dalis 2: [5 6 7]
  dalis 3: [ 8  9 10]


In [17]:
mat = np.arange(1, 13).reshape(3, 4)
print("mat =\n", mat)

# hsplit: skaidymas pagal stulpelius
left, right = np.hsplit(mat, 2)

print("Kairė pusė (hsplit) =\n", left)
print("Dešinė pusė (hsplit) =\n", right)

mat =
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
Kairė pusė (hsplit) =
 [[ 1  2]
 [ 5  6]
 [ 9 10]]
Dešinė pusė (hsplit) =
 [[ 3  4]
 [ 7  8]
 [11 12]]


In [18]:
mat = np.arange(1, 13).reshape(3, 4)
print("mat =\n", mat)

# vsplit: skaidymas pagal eilutes
top, bottom = np.vsplit(mat, [1])  # pirmos eilutės blokas ir likusi dalis

print("Viršus (pirma eilutė) =\n", top)
print("Apačia (likusios eilutės) =\n", bottom)

mat =
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
Viršus (pirma eilutė) =
 [[1 2 3 4]]
Apačia (likusios eilutės) =
 [[ 5  6  7  8]
 [ 9 10 11 12]]


## 7. Trumpa santrauka

- `reshape` keičia formą nekeisdamas elementų kiekio.
- `flatten` grąžina 1D masyvo kopiją, `ravel` dažnai grąžina vaizdą (view).
- `concatenate` sujungia masyvus pagal pasirinktą `axis`.
- `vstack` ir `hstack` yra patogūs trumpiniai 2D sujungimui.
- `column_stack`, `row_stack`, `dstack` padeda patogiai sujungti masyvus įvairiais būdais.
- `split`, `array_split`, `hsplit`, `vsplit` leidžia suskaidyti masyvus į dalis.